### ISSUE TITLE
HalExplorer\Hypermedia\Parser->getEmbed(ResponseInterface $response, $id) can return array of objects, not just a single one

### ISSUE THREAD

**Issue by MaurizioMoreo** [Jmeyering/hal-explorer#11]
As in the [HAL draft "_embedded" section](https://tools.ietf.org/html/draft-kelly-json-hal-06#section-4.1.2) the response is an object with link relation types as properties, but when you get one of them, it can contain either a resource object or an array of resource objects. I think that the function should be able to return a simple stdClass or an array of them (if it's correct, maybe using two functions with different return types?)

**Comment by Jmeyering** [comment]
Currently the function just returns the embed at the associated id. If the embed is an array it will return the array. Using an array as a key within the "embedded" section is against spec however. I think adding functionality to convert the array to an array of resources is unwise. 

Let me know if I've misunderstood the request.
