### ISSUE TITLE
Adapter::patch() is missing but declared in AdapterInterface

### ISSUE THREAD

**Issue by ureimers** [Jmeyering/hal-explorer#7]
Sorry to bother you again but, as stated in the issue's description, the Adapter currently creates PHP errors because it doesn't implement the patch() method.

When I'm getting more confident with Git(Hub) I will create pull requests but for now I think what is missing is only:

``` php
    /**
     * Perform a patch request
     *
     * @param string $uri
     * @param array  $options All options for the request, will be passed to the
     * client
     *
     * @return ResponseInterface
     */
    public function patch($uri, array $options = [])
    {
        return $this->getClient()->patch($uri, $options);
    }
```

**Comment by Jmeyering** [comment]
Good find! Fixed in latest release.
