### ISSUE TITLE
Overriding "Content-Type" header for multipart-posts not possible

### ISSUE THREAD

**Issue by ureimers** [Jmeyering/hal-explorer#9]
Hi, it's me again ;-)

I just tried to do a multipart post on our client's HAL-API and had a really hard time setting the "Content-Type"-Header. It's set by default to "application/json" but for something like this to work:

```
        $this->explorer->createRelation($this->enter(), 'documents', [
            'multipart' => [
                [
                    'name'     => 'content',
                    'filename' => 'filename',
                    'contents' => $data,
                ]
            ]
        ]
```

...the "Content-Type" must be empty, so that Guzzle sets is on its own.

I accomplished that by calling:

```
       $this->explorer->setDefaults(function ($original) {
            $original["headers"]["Authorization"] = 'bearer '.$this->getAuthorizationToken();
            unset($original["headers"]["Content-Type"]);

            return $original;
        });
```

As there's no "getConfiguredDefaultCallback" I couldn't write a workaround like:
1. Get current callback
2. Define a new one that removes the "Content-Type" header
3. Reset to the old callback

So it is possible but very cumbersome and hard to reset afterwards.

Any ideas?

**Comment by ureimers** [comment]
Maybe a solution would be an optional `options` closure just like `defaults`, so that in ``Exploder::makeRequest():114` you'll end up with something like:

``` php
$options = array_merge_recursive(
  $this->getDefaults(),
  !empty($this->options) ? call_user_func($this->options, $options) : [],
  $options
);

// or (to include the default options too)

$options = array_merge_recursive($this->getDefaults(), $options);
if (!empty($this->options)) {
  $options = call_user_func($this->options, $options);
}
```

That would be adapter-independent. For the problem mentioned in this ticket the callback then could look like:

``` php
function($options) {
  // Let Guzzle handle the Content-Type for multipart requests.
  if (isset($options['multipart'])) {
    unset($options['headers']['Content-Type']);
  }
}
```

**Comment by Jmeyering** [comment]
The explorer defaults are never actually overwritten. 

```
       $this->explorer->setDefaults(function ($original) {
            $original["headers"]["Authorization"] = 'bearer '.$this->getAuthorizationToken();
            unset($original["headers"]["Content-Type"]);

            return $original;
        });
        //
        // Code here
        //
        $this->explorer->setDefaults(function($a){
            return $a;
        });
```

Should reset the defaults to original

**Comment by ureimers** [comment]
Yes, I understand. 

Currently I created a closure to fit all my needs and hope that there aren't any special needs for the headers in the future:

``` php
function ($original) {
  $original["headers"]["Authorization"] = 'bearer '.$this->getAuthorizationToken();

  if ($this->skipContentTypeForNextRequest) {
    // This lets guzzle define the content type. Needed for multipart requests to work.
    unset($original["headers"]["Content-Type"]);
    $this->skipContentTypeForNextRequest = false;
  }

  return $original;
}
```

This still doesn't feel right. I need to set a helper variable to make the next request remove the Content-Type header. Currently there's no other way (except switching the entire closure for one request, and reverting to my default one after that, which isn't much better as I need to store my default closure in a helper variable to restore it later).

What do you think about the `options` closure? I think that it could really help. The `defaults` closure set the default values for _all_ requests while the `options` closure is there to alter the defaults based on the _current_ request options.

Or you could simply pass the current options to the `defaults` closure. Then it would simply be:

``` php
$this->explorer->setDefaults(function ($original, $options) {
  $original["headers"]["Authorization"] = 'bearer '.$this->getAuthorizationToken();

  // Let Guzzle handle the Content-Type for multipart requests.
  if (isset($options['multipart'])) {
    unset($original['headers']['Content-Type']);
  }

  return $original;
});
```

Regards
